AWSTemplateFormatVersion: 2010-09-09
Description:
  VPC & subnet create

Resources: 
  VpcForCf:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: VpcForCf

  IgwForCf:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IgwForCf
  AttachIgwForCf:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcForCf
      InternetGatewayId: !Ref IgwForCf


  RoutePublicsubnet:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcForCf
      Tags:
        - Key: Name
          Value: Rt-publicsubnet

  RoutePublic:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RoutePublicsubnet
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IgwForCf
      
  PublicSubnetForCf01:
    Type: AWS::EC2::Subnet
    Properties:
        AvailabilityZone:
          Fn::Select: 
            - 0
            - Fn::GetAZs: ""
        VpcId: !Ref VpcForCf
        CidrBlock: 10.0.0.0/20
        Tags:
        - Key: Name
          Value: PublicSubnetForCf01
        
  RouteTableAssocPublic01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetForCf01
      RouteTableId: !Ref RoutePublicsubnet

  PublicSubnetForCf02:
    Type: AWS::EC2::Subnet
    Properties:
        AvailabilityZone:
          Fn::Select: 
            - 1
            - Fn::GetAZs: ""
        VpcId: !Ref VpcForCf 
        CidrBlock: 10.0.16.0/20
        Tags:
        - Key: Name
          Value: PublicSubnetForCf02
          
  RouteTableAssocPublic02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetForCf02
      RouteTableId: !Ref RoutePublicsubnet

  RoutePrivatesubnet:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcForCf
      Tags:
        - Key: Name
          Value: Rt-privatesubnet

  PrivateSubnetForCf01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      VpcId: !Ref VpcForCf
      CidrBlock: 10.0.128.0/20
      Tags:
        - Key: Name
          Value: PrivateSubnetForCf01
  
  RouteTableAssocPrivate01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetForCf01
      RouteTableId: !Ref RoutePrivatesubnet

  PrivateSubnetForCf02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select: 
          - 1
          - Fn::GetAZs: ""
      VpcId: !Ref VpcForCf
      CidrBlock: 10.0.144.0/20
      Tags:
        - Key: Name
          Value: PrivateSubnetForCf02

  RouteTableAssocPrivate02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetForCf02
      RouteTableId: !Ref RoutePrivatesubnet
  

Outputs:
  StackVPC:
    Description: The ID of the VPC
    Value: !Ref VpcForCf
    Export:
      Name: VPCID

  StackPublicSubnet01:
    Description: The ID of the VPC Subnet
    Value: !Ref PublicSubnetForCf01
    Export:
      Name: PublicSubnet01

  StackPublicSubnet02:
    Description: The ID of the VPC Subnet
    Value: !Ref PublicSubnetForCf02
    Export:
      Name: PublicSubnet02

  StackPrivateSubnet01:
    Description: The ID of the VPC Subnet
    Value: !Ref PrivateSubnetForCf01
    Export:
      Name: PrivateSubnet01

  StackPrivateSubnet02:
    Description: The ID of the VPC Subnet
    Value: !Ref PrivateSubnetForCf02
    Export:
      Name: PrivateSubnet02
